### ISSUE TITLE
Unauthorized/404 response to libraries API

### ISSUE THREAD

**Issue by andycasey** [adsabs/adsabs-dev-api#23]
Hola compadres,

I've branched the ADS client with the aim to make use of the libraries API, but I am encountering some rudimentary troubles. In short, I am getting 404's or unauthorized responses to a simple get method to list all my private libraries:

````
 ads arc$ curl -H 'Authorization: Bearer <TOKEN>' 'https://api.adsabs.harvard.edu/v1/biblib/'
{
  "error": "Not found"
}ads arc$ curl -H 'Authorization: Bearer <TOKEN>' 'https://api.adsabs.harvard.edu/v1/biblib'
{
  "error": "Not found"
}ads arc$ curl -H 'Authorization: Bearer <TOKEN>' 'https://api.adsabs.harvard.edu/v1/biblib/libraries'
{
  "error": "Unauthorized"
}ads arc$ curl -H 'Authorization: Bearer <TOKEN>' 'https://api.adsabs.harvard.edu/v1/biblib/libraries/'
{
  "error": "Unauthorized"
}
````
(Obviously, `<TOKEN>` has been replaced here with my real token)

I have one library in BBB, which is public but has no documents. Where have I screwed up here?

Thanks!

**Comment by jonnybazookatone** [comment]
I'll take a look. Most likely related to our internal scopes (permissions) that have 'user' scope. The ones that don't have this scope (I think libraries/library_id is the only one) should work for the time being.

**Comment by andycasey** [comment]
Thanks @jonnybazookatone.

The `library_id` seems to be only available through the API (I cannot find it on the BBB UI). For that reason I can't seem to confirm on my side whether `libraries/library_id` works for me or not because I can't create a new library via the API or get the IDs of existing ones created via the UI.

Let me know if there's anything I can do to help debug.

**Comment by jonnybazookatone** [comment]
(a slightly hackish way) You can get the ID by going to 'Manage Permissions' via the button on your libraries page and press 'make public', and the URL it gives you has an ID at the end, e.g.,  
`ui.adsabs.harvard.edu/#/public-libraries/PMOjzfbbTZKShRWvIZF6cg`

the library id here is `PMOjzfbbTZKShRWvIZF6cg`. I tested and this works. Don't worry about any debugging, I'll let you know once I've put a fix in place.

Sorry it didn't work straight off the bat.

**Comment by andycasey** [comment]
Thanks for the library ID tip. No need to apologise!

**Comment by jonnybazookatone** [comment]
Should be working now. JSON variable defined with '' instead of "" can cause a little bit of havoc :-).

**Comment by andycasey** [comment]
Hmm, I'm still having troubles on my end:

````
arc$ curl -H 'Authorization: Bearer <API_TOKEN>' 'https://api.adsabs.harvard.edu/v1/biblib/libraries'
{
  "error": "Unauthorized"
}
arc$ curl -H 'Authorization: Bearer <API_TOKEN>' 'https://api.adsabs.harvard.edu/v1/biblib/libraries/'
{
  "error": "Unauthorized"
}
````

My ADS username is arc, should I email you my API token to see if you get the same behaviour using my token on your end?

**Comment by jonnybazookatone** [comment]
Don't worry, I had your token, I just tried the wrong one. It should work now - let me know if it doesn't

```
curl -H "Authorization: Bearer <TOKEN>" https://api.adsabs.harvard.edu/v1/biblib/libraries
{"libraries": [{"num_documents": 0, "date_last_modified": "2015-11-04T21:03:58.873838",
......
}]}
```

**Comment by andycasey** [comment]
Woohoo! It works. Thanks @jonnybazookatone!
