### ISSUE TITLE
Some papers not associated with their publications?

### ISSUE THREAD

**Issue by nevencaplar** [adsabs/adsabs-dev-api#28]
Hi

I noticed this interesting behavior in which some papers are not "recognized" to be belonging to publications in which they were published. Minimal working example with a random paper:

?q="pub:Astronomy+and+Astrophysics+identifier:1998A%26A...331..601I"

responds with

{"responseHeader":{"status":0,"QTime":18,"params":{"q":"pub:Astronomy and Astrophysics identifier:1998A&A...331..601I","fl":"id","wt":"json"}},"response":{"numFound":0,"start":0,"docs":[]}}

i.e. this file was not found. But the the paper with this identifier exists (and its "pub" value is exactly Astronomy and Astrophysics! ), and there is a positive response where executing the same command without pub part..

?q="identifier:1998A%26A...331..601I".

This happens only rarely, most of the time there is no problem. For instance, 

?q="pub:Astronomy+and+Astrophysics+identifier:1999A%26A...341....8R"

responds with positive find without any problems, as do many others.

Is this a problem in the database, or am I seriously misunderstanding something?

**Comment by adsabs-beer-user** [comment]
Hi Neven,

Your query (once unencoded) looks like this:

pub:Astronomy and Astrophysics identifier:1998A&A...331..601I

which means: find all papers with "Astronomy" in the publication field, AND
with 1998A&A...331..601I in the identifier field AND with "Astrophysics"
anywhere in the other default search fields (abstract, title, etc).

What you want instead is to search for "Astronomy and Astrophysics" in the
publication field like so:

pub:"Astronomy and Astrophysics" identifier:1998A&A...331..601I

This will provide you with the desired results:
https://ui.adsabs.harvard.edu/#search/q=pub%3A%22Astronomy%20and%20Astrophysics%22%20identifier%3A1998A%26A...331..601I&sort=date%20desc%2C%20bibcode%20desc

Note however that a better search would be to use the bibstem and bibcode
fields:

bibstem:A&A bibcode:1998A&A...331..601I

The items in "bibstems" come from a controlled dictionary so the search is
more accurate.  To convince yourself of this you can check the different
results between the following two searches:

https://ui.adsabs.harvard.edu/#search/q=pub%3A%22Astronomy%20and%20Astrophysics%22%20&sort=date%20desc%2C%20bibcode%20desc

https://ui.adsabs.harvard.edu/#search/q=bibstem%3AA%26A&sort=date%20desc%2C%20bibcode%20desc

-- Alberto




On Wed, Jun 8, 2016 at 4:55 PM, Neven Caplar <notifications@github.com>
wrote:

> Hi
>
> I noticed this interesting behavior in which some papers are not
> "recognized" to be belonging to publications in which they were published.
> Minimal working example with a random paper:
>
> ?q="pub:Astronomy+and+Astrophysics+identifier:1998A%26A...331..601I"
>
> responds with
>
> {"responseHeader":{"status":0,"QTime":18,"params":{"q":"pub:Astronomy and
> Astrophysics
> identifier:1998A&A...331..601I","fl":"id","wt":"json"}},"response":{"numFound":0,"start":0,"docs":[]}}
>
> i.e. this file was not found. But the the paper with this identifier
> exists (and its "pub" value is exactly Astronomy and Astrophysics! ), and
> there is a positive response where executing the same command without pub
> part..
>
> ?q="identifier:1998A%26A...331..601I".
>
> This happens only rarely, most of the time there is no problem. For
> instance,
>
> ?q="pub:Astronomy+and+Astrophysics+identifier:1999A%26A...341....8R"
>
> responds with positive find without any problems, as do many others.
>
> Is this a problem in the database, or am I seriously misunderstanding
> something?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adsabs/adsabs-dev-api/issues/28>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHURkWdRuwOQn14KsMhvOy5OpTvS0_hoks5qJyxDgaJpZM4IxZEK>
> .
>



-- 
Dr. Alberto Accomazzi
Principal Investigator
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Comment by nevencaplar** [comment]
Ok great, I will have a look and come back if I have more questions

**Comment by jonnybazookatone** [comment]
Please re-open if you have any further problems/issues.
