### ISSUE TITLE
Year field not respected

### ISSUE THREAD

**Issue by borisrev** [adsabs/adsabs-dev-api#33]
curl -H "Authorization: Bearer mytoken" "https://api.adsabs.harvard.edu/v1/search/bigquery?q=aff:%22harvard%22&year:2001&rows=10&fl=doi,title,year"

Returns items from many different years. I've tried surrounding 2001 with %22 (quotes), but no dice. I also tried the [year to year] format but similarly had no luck.

Thank you again! (And for your quick reply to the last issue!)

Thank you,
Boris

**Comment by romanchyla** [comment]
that's because the 'year:2001' must be a part of the query ('q' parameter)

q=aff:%22harvard%22+AND+year:2001

**Comment by borisrev** [comment]
Great. Thank you very much.
