### ISSUE TITLE
Add entry date to indexed fields in Search API

### ISSUE THREAD

**Issue by seweissman** [adsabs/adsabs-dev-api#35]
Hi. We are working at MAST to upgrade our bibliographic software to use the new ADS API. Our staff prefers to use the entry date search provided by the current ADS form (http://adsabs.harvard.edu/abstract_service.html) to search for new publications in the database. Would it be possible to get this field added to the API? Right now only pubdate and indexstamp appear to be available.

**Comment by ehenneken** [comment]
Hi Sarah. We are planning on adding an entry date field, but we don't have an ETA for that as yet. It will definitely come!

**Comment by adsabs-beer-user** [comment]
To provide a bit of context: we are testing new version of our pipeline -
this makes it possible to record entry date more easily. So it is not like
distant future, but we don't like to over-promise. Stay tuned!

**Comment by seweissman** [comment]
Thanks!

**Comment by seweissman** [comment]
Any update on this?

**Comment by aaccomazzi** [comment]
Now implemented via the `entry_date` field and the `entdate` search parameter.  For more information, please see: https://adsabs.github.io/help/search/comprehensive-solr-term-list
