### ISSUE TITLE
Dumping all personal libraries into a bibtex file

### ISSUE THREAD

**Issue by ferrigno** [adsabs/adsabs-dev-api#65]
Dear Developers,

I was struggling in the past to collect references and then had to redo the job again and again. Using ADS personal libraries is very convenient. However, for a large number of libraries exporting can become cumbersome. 
I have written a python script, using some of the code made available on these pages to dump personal libraries in a local bibtex file: it is at
https://gitlab.astro.unige.ch/ferrigno/adslibraries
and available in pip 
pip install adslibraries

Should you find it useful, you could put a link somewhere.
I will likely develop some features if I need them in the future.

Best wishes,
Carlo

**Comment by ehenneken** [comment]
Dear Carlo

That's great. Thank you for sharing your code!

cheers
Edwin

*Edwin Henneken*

*Content & Curation Lead*

NASA Astrophysics Data System

Center for Astrophysics | Harvard & Smithsonian

60 Garden Street | MS 83 | Cambridge, MA 02138


ads.harvard.edu | @adsabs <https://twitter.com/adsabs> | *ui.adsabs.harvard.edu
<https://ui.adsabs.harvard.edu/>*

*cfa.harvard.edu <https://cfa.harvard.edu/>* | Facebook
<http://cfa.harvard.edu/facebook> | Twitter <http://cfa.harvard.edu/twitter>
| YouTube <http://cfa.harvard.edu/youtube> | Newsletter
<http://cfa.harvard.edu/newsletter>
