### ISSUE TITLE
What are the constraints on library names

### ISSUE THREAD

**Issue by gmella** [adsabs/adsabs-dev-api#69]
First, thank a lot for your API and associated services which help us a lot to combine multiples tools.
( it could be fun (or I like to imagine) to set VO/SAMP on both tool so we can do more than the sum of the two services ;) )

I then created many libraries using names coming from another database. I get a 500 error with message="INTERNAL SERVER ERROR" for one of them.
I guess that it is related to the maximum length allowed for the name field.

Is there a way to get a better error message ? 

I double check the documentation but did not find any word about such constraint that can help to design code.

Regards,
--
Guillaume

**Comment by marblestation** [comment]
This looks to me more like a bug on our end, could you send to adshelp@cfa.harvard.edu an example of a requests that fails? Thanks!
