### ISSUE TITLE
open access property wrong

### ISSUE THREAD

**Issue by birnstiel** [adsabs/adsabs-dev-api#7]
All articles from my query seem to be marked with the property "OPENACCESS", even those, which should not be, such as recent A&A papers which become open access only after 1 year and should therefore only marked as "EPRINT_OPENACCESS" in case they are on arXiv.

Example:

    import json, urllib2, os
    DEVKEY = os.environ['ADS_DEV_KEY']
    DOI='10.1051/0004-6361/201424669'
    URL = r'http://adslabs.org/adsabs/api/search/?q=doi:"'+DOI+'"&dev_key=' + DEVKEY
    PUBS = json.load(urllib2.urlopen(URL))['results']['docs']
    if 'OPENACCESS' in PUBS[0]['property']:
        print('article in open access')
    elif 'EPRINT_OPENACCESS' in PUBS[0]['property']:
        print('article in green open access')
    else:
        print('article NOT in open access')

Result:

    article in open access

But the article is [not open access](http://dx.doi.org/10.1051/0004-6361/201424669).

**Comment by adsabs-beer-user** [comment]
Hi Kevin,

The semantics for these properties are as follow:

EPRINT_OPENACCESS: there is an eprint version for this paper which is open
access
PUB_OPENACCESS: there is a publisher full-text article which is open access
ADS_OPENACCESS: there is an ADS-provided version of the article which is
openaccess
OPENACCESS = EPRINT_OPENACCESS | PUB_OPENACCESS | ADS_OPENACCESS

i.e. "OPENACCESS" when set, tells you that there is at least one version of
the paper which is freely available.

-- Alberto


On Mon, Mar 16, 2015 at 12:00 PM, birnstiel <notifications@github.com>
wrote:

> All articles from my query seem to be marked with the property
> "OPENACCESS", even those, which should not be, such as recent A&A papers
> which become open access only after 1 year and should therefore only marked
> as "EPRINT_OPENACCESS" in case they are on arXiv.
>
> Example:
>
> import json, urllib2, os
> DEVKEY = os.environ['ADS_DEV_KEY']
> DOI='10.1051/0004-6361/201424669'
> URL = r'http://adslabs.org/adsabs/api/search/?q=doi:"'+DOI+'"&dev_key=' + DEVKEY
> PUBS = json.load(urllib2.urlopen(URL))['results']['docs']
> if 'OPENACCESS' in PUBS[0]['property']:
>     print('article in open access')
> elif 'EPRINT_OPENACCESS' in PUBS[0]['property']:
>     print('article in green open access')
> else:
>     print('article NOT in open access')
>
> Result:
>
> article in open access
>
> But the article is not open access
> <http://dx.doi.org/10.1051/0004-6361/201424669>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/adsabs-dev-api/issues/7>.
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Comment by birnstiel** [comment]
My name is not Kevin, but thanks for the explanation! Is there some website where I could have found that information?

**Comment by birnstiel** [comment]
Ok, I already found a mentioning [here](http://labs.adsabs.harvard.edu/adsabs/page/help/search). Is it also possible to query personal libraries using the `libname` and `libid`?

**Comment by adsabs-beer-user** [comment]
Hi Keith (hope I got it right this time).

At this point the personal libraries are not integrated through our API,
although it's in our plans once we port them from ADS classic to the new
system.

You have two options to access them programmatically:

1. use the search engine directly requesting XML output, e.g.
http://adsabs.harvard.edu/cgi-bin/abs_connect?library&libname=HerschelPapers&libid=4c44938764&data_type=XML

2. use an export script which generates json output:
http://adsabs.harvard.edu/cgi-bin/export_privlib?libid=4c44938764&libname=HerschelPapers

Hope this helps,
-- Alberto



On Mon, Mar 16, 2015 at 4:24 PM, birnstiel <notifications@github.com> wrote:

> Ok, I already found a mentioning here
> <http://labs.adsabs.harvard.edu/adsabs/page/help/search>. Is it also
> possible to query personal libraries using the libname and libid?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/adsabs-dev-api/issues/7#issuecomment-81918563>.
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Comment by a6073758** [comment]
Hi Alberto!

No, still not the right name! Where do you get these names from? Should be easy to find out my name based on this thread! Hint: I'm not very far from you. :smiley: 

Anyway: thanks a lot for the answer. I also found that the ADS 2.0 libraries can be queried based on their identifier, for example:

http://adslabs.org/adsabs/api/search/?dev_key=DEVKEY&q=%2A%3A%2A&bigquery=3c1ffb0f-728c-4780-b78c-6e7c4d08997d

**Comment by birnstiel** [comment]
Hi Alberto!

No, still not the right name! Where do you get these names from? Should be easy to find out my name based on this thread! Hint: I'm not very far from you. :smiley:

Anyway: thanks a lot for the answer. I also found that the ADS 2.0 libraries can be queried based on their identifier, for example:

http://adslabs.org/adsabs/api/search/?dev_key=DEVKEY&q=%2A%3A%2A&bigquery=3c1ffb0f-728c-4780-b78c-6e7c4d08997d

**Comment by adsabs-beer-user** [comment]
Ah, silly me, I was looking at the name that gmail associated with
notifications@github.com (the sender of these messages), sorry about that.
So I actually still don't know who you are, not that it matters...

Be aware that when you view papers from one of your libraries in ADS 2.0
using the "bigquery" option, they are saved in a temporary cache, so the
contents are not going to persist (and they won't reflect further changes
in the library).  In other words, the hash created by the query and
identifying the papers is ephemeral.

-- Alberto


On Mon, Mar 16, 2015 at 9:00 PM, birnstiel <notifications@github.com> wrote:

> Hi Alberto!
>
> No, still not the right name! Where do you get these names from? Should be
> easy to find out my name based on this thread! Hint: I'm not very far from
> you. [image: :smiley:]
>
> Anyway: thanks a lot for the answer. I also found that the ADS 2.0
> libraries can be queried based on their identifier, for example:
>
>
> http://adslabs.org/adsabs/api/search/?dev_key=DEVKEY&q=%2A%3A%2A&bigquery=3c1ffb0f-728c-4780-b78c-6e7c4d08997d
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/adsabs-dev-api/issues/7#issuecomment-82012108>.
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Comment by birnstiel** [comment]
Oh, I see! I'll try your export script then. Thanks!

**Comment by adsabs-beer-user** [comment]
And in that cade be aware that the script will only export libraries from
ADS classic.

Alberto

**Comment by birnstiel** [comment]
Thanks! The export script only returns the bibcodes, not the full entries. Is there a way to query all those bib codes? The ADS 2.0 search seems to support only one `bibcode:` search.
