### ISSUE TITLE
Support: Mailing list google group?

### ISSUE THREAD

**Issue by vsudilov** [adsabs/adsabs-dev-api#8]
@aaccomazzi , could you please comment on the validity of the following statement? Should that be updated?

`Announcements and discussion related to the Developer API are available via the Google Group, [adsabs-dev-api](https://groups.google.com/forum/#!forum/adsabs-dev-api). We encourage all API users to subscribe, as the functionality of the API, format of responses, etc., will likely be improving and changing rapidly.`

**Comment by aaccomazzi** [comment]
The group does exist and we should use it as a way to announce the upcoming changes, so I would not change any of that text.

**Comment by vsudilov** [comment]
The forum that active, and it requires us to look into two places for comments: github issues and the forum. How about just using github issues for feedback/suggestions?

**Comment by aaccomazzi** [comment]
It's mostly for announcements.  Subscribers get an email, so you don't have to worry and go read the group on a regular basis (nor check issues).  I think it's worth keeping it.
