### ISSUE TITLE
Question: Is there a way to perform a query with first affiliation?

### ISSUE THREAD

**Issue by Mulan-94** [adsabs/adsabs-dev-api#83]
Hello,

I would like to ask if there is a way to perform a query for selecting papers depending only on the first author's affiliation, or just the first affiliation?

Thank you!

**Comment by csgrant00** [comment]
Lexy,
Use the "pos" operator:

pos(aff:"Harvard University",1)

Thank you also for the correction of the typo in our affiliation list.
-Carolyn

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 ***@***.***        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************
