### ISSUE TITLE
No verification email sent

### ISSUE THREAD

**Issue by andycasey** [adsabs/adsabs-dev-api#9]
Hey guys,

I signed up for a new account (arc@ast.cam.ac.uk) at https://ui.adsabs.harvard.edu/ about 15 minutes ago but haven't got a verification email yet. Is this standard (i.e., should I keep waiting) or is there something amiss here?

Thanks,
Andy

**Comment by andycasey** [comment]
Nevermind; sorry!

**Comment by vsudilov** [comment]
Hi @andycasey, just to followup -- was the problem that the email was classified as spam?

**Comment by andycasey** [comment]
Nope, it just arrived a few minutes after opening the issue (and it was not marked as spam when it arrived). I guess I was just too eager!
